version: '3.8'
services:
  player-service:
    build: ./player-service
    ports:
      - "8001:8000"  # El puerto local 8001 mapea al puerto 8000 del contenedor
    depends_on:
      - mongo  # Dependencia de MongoDB
    networks:
      - football_network  # Definir una red para la comunicación entre servicios

  team-service:
    build: ./team-service
    ports:
      - "8002:8000"
    depends_on:
      - mongo
    networks:
      - football_network

  stats-service:
    build: ./stats-service
    ports:
      - "8003:8000"
    depends_on:
      - mongo
    networks:
      - football_network

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"  # Mapea el puerto local 27018 al puerto 27017 del contenedor
    networks:
      - football_network
    volumes:
      - mongo_data:/data/db

# Definir redes personalizadas para los servicios
networks:
  football_network:
    driver: bridge

# Declarar volúmenes persistentes
volumes:
  mongo_data:

